### ISSUE TITLE
Validate Traction 0.3.0 Upgrade

### ISSUE THREAD

**Issue by i5okie** [bcgov/DITP-DevOps#98]
Look into the observed issue with upgrading Traction `dev` and `test` instances to 0.3.0 version.

The following issue was observed during an upgrade. It is uncertain if this is the result of misconfiguration or an issue with wrong code in built image.
```
2023-08-15 19:51:44,409 aries_cloudagent.core.event_bus ERROR Error occurred while processing event
Traceback (most recent call last):
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/core/event_bus.py", line 121, in notify
    await processor()
  File "/home/aries/traction_plugins/traction_innkeeper/v1_0/innkeeper/__init__.py", line 49, in on_startup
    await mgr.create_innkeeper()
  File "/home/aries/traction_plugins/traction_innkeeper/v1_0/innkeeper/tenant_manager.py", line 167, in create_innkeeper
    tenant_record, wallet_record, token = await self.create_wallet(
  File "/home/aries/traction_plugins/traction_innkeeper/v1_0/innkeeper/tenant_manager.py", line 83, in create_wallet
    wallet_record = await multitenant_mgr.create_wallet(
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/multitenant/base.py", line 184, in create_wallet
    await wallet_record.save(session)
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/messaging/models/base_record.py", line 372, in save
    await storage.add_record(self.storage_record)
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/messaging/models/base_record.py", line 136, in storage_record
    self.RECORD_TYPE, json.dumps(self.value), self.tags, self._id
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/aries/.venv/lib/python3.9/site-packages/frozendict/__init__.py", line 32, in default
    return BaseJsonEncoder.default(self, obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type EndorserLedgerConfig is not JSON serializable
```

**Comment by esune** [comment]
Please note that the issue *might* have been caused by me trying to run the wrong version of the chart (current `main`) against the `0.3.0` image tag. The task is to validate the `0.3.0` tag works correctly and upgrade the `test` deployment when confirmed.

**Comment by i5okie** [comment]
`0.3.0` validated. 
`test` deployments have been upgraded.
